name: rongheguai

on:
  workflow_dispatch:

jobs:
  scrawler:
    runs-on: ubuntu-latest

    steps:
      - name: 融合怪
        run: export noninteractive=true && curl -L https://raw.githubusercontent.com/oneclickvirt/ecs/master/goecs.sh -o goecs.sh && chmod +x goecs.sh && bash goecs.sh env && bash goecs.sh install && goecs
