name: rongheguai

on:
  workflow_dispatch:

jobs:
  scrawler:
    runs-on: ubuntu-latest

    steps:
      - name: 融合怪
        run: curl -L https://gitlab.com/spiritysdx/za/-/raw/main/ecs.sh -o ecs.sh && chmod +x ecs.sh && bash ecs.sh -m 1
